ar:
	g++ array.cpp -o ./exe/array
	./exe/array
ve:
	g++ vector.cpp -o ./exe/vector
	./exe/vector
de:
	g++ deque.cpp -o ./exe/deque
	./exe/deque	
li:
	g++ list.cpp -o ./exe/list
	./exe/list
fli:
	g++ forward_list.cpp -o ./exe/forward_list	
	./exe/forward_list

