fp:
	g++ function_pointer.cpp -o ./exe/function_pointer
	./exe/function_pointer
lambda:
	g++ lambda.cpp -o ./exe/lambda
	./exe/lambda
functor:
	g++ functor.cpp -o ./exe/functor
	./exe/functor
functor_2:
	g++ functor_2.cpp -o ./exe/functor_2
	./exe/functor_2
iterator:
	g++ iterator.cpp -o ./exe/iterator
	./exe/iterator
bind:
	g++ bind.cpp -o ./exe/bind
	./exe/bind
random:
	g++ random.cpp -o ./exe/random
	./exe/random
f_s:
	g++ functor_sorting.cpp -o ./exe/functor_sorting
	./exe/functor_sorting
